# This is a basic workflow to help you get started with Actions

name: Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Release_PKG:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release [${{ github.event.head_commit.message }}]
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          title: Release ${{ github.event.head_commit.message }}

      - name: Upload Package to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          file: ${{ github.workspace }}/doc2scan-macos-installer-x64/doc2scan-macos-installer-x64-${{ github.event.head_commit.message }}.pkg
          asset_name: doc2scan-macos-installer-x64/doc2scan-macos-installer-x64-${{ github.event.head_commit.message }}.pkg
          overwrite: true

      
