name: Release
on:
  push:


jobs:
  MacRelease:
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[[0-9]+.[0-9]+.[0-9]+]')"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Create Release [${{ github.event.head_commit.message }}]
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        with:
          title: Release ${{ github.event.head_commit.message }}

      - name: Upload Package to Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.REPO_ACCESS_TOKEN }}
          file: ${{ github.workspace }}/doc2scan-macos-installer-x64/doc2scan-macos-installer-x64-${{ github.event.head_commit.message }}.pkg
          asset_name: doc2scan-macos-installer-x64-${{ github.event.head_commit.message }}.pkg
          overwrite: true

      
